### ISSUE TITLE
Vocal Transcription not working in the colab notebook

### ISSUE THREAD

**Issue by vumaasha** [Music-and-Culture-Technology-Lab/omnizart#19]
Steps to reproduce

1. Open notebook
2. upload an mp3 file
3. Choose mode = vocal
4. Transcription fails with the error below

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/1514670/117148556-f2508500-add3-11eb-950f-75a41dcc3f9c.png">

There are also some errors in the environment setup section of the notebook. I will be happy to help if any further details/tests are needed

**Comment by BreezeWhite** [comment]
Thank you for reporting this bug. I've fixed the bug and released a new version now. You should now able to use vocal transcription.

**Comment by vumaasha** [comment]
Hi,
Issue still exists while running on colab. I get a different error now though.

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/1514670/117431639-184a6680-af47-11eb-8b3e-8b1447254ee2.png">

**Comment by BreezeWhite** [comment]
Oops. This time should work now 😅

**Comment by vumaasha** [comment]
Hey it worked thanks. A couple of follow up questions

1. How does it work behind the scene? Any papers or pointers or docs?
2. The results are great but still far from perfect, is there a way to improve them by additional training etc?

**Comment by BreezeWhite** [comment]
1. You can find the documentation site from the description of this project. Here provided for you: [document](https://music-and-culture-technology-lab.github.io/omnizart-doc/).

2. Yes, you can continue to train on the provided checkpoint by using your own data. More information can be found from the documentation.
